data/ice-shard/Custom.css

+ Made the message search colors consistent with the theme
+ Changed some text on light backgrounds to dark for readability
+ Made formatting more consistent

Update Ice Shard theme's css

---

data/nocturnal/Preset.toml

Nocturnal theme

---

data/ice-shard/Custom.css
data/ice-shard/Preset.toml

+ bumped up to latest commit
+ added outlines around some less visible elements
+ improved descriptions

feat: Updated Ice Shard

---

data/rosepine-dawn/Preset.toml
data/rosepine-moon/Preset.toml
data/rosepine/Preset.toml

Add the 3 Rosé Pine themes (Rosé Pine, Rosé Pine Moon, and Rosé Pine Dawn) from https://github.com/rose-pine/revolt / https://rosepinetheme.com/.

feat: add Rosé Pine themes.

---

data/nocturnal/Preset.toml

The previous color is making chat hard to see when you have weird eyes and the search bar is kinda of weird when using the old color

fix(nocturnal): changed primary background color

---

data/rexo-turquoise/Preset.toml

This PR adds a dark turquoise theme.

feat: add Rexo's Turquoise Theme

---

data/one-dark/Preset.toml

_This theme (and the screenshot) were made by @Odyssey346. I am committing it on his behalf._

feat: add One Dark theme

---

data/nocturnal/Preset.toml

Change scrollbar thumb color to fix issue in #467 in revite repo.

Fix(Nocturnal): Change scrollbar thumb color

---

data/discord-colors/Preset.toml

fix: fix discord colors theme

---

data/discord-colors/Custom.css

feat: create Custom.css

---

data/deep-ocean/Preset.toml

I created the Theme deep-ocean inspired by  
🌌 The VSCode Theme [Ocean Space](https://github.com/oscarmcm/ocean-space)   
and    
🌊 The Hyper.js Theme[ Hyperocean](https://github.com/klaussinani/hyperocean)

feat: added deep-ocean 🌊

---

data/irc-chat/Preset.toml

Fix the theme issue

---

data/amethyst/Preset.toml

Adds amethyst theme based on [Amethyst BetterDiscord](https://github.com/spinfish/amethyst).

add amethyst theme

---

data/comfy-blue/Preset.toml

add comfy blue theme

---

data/horizon/Preset.toml

Style: Add Horizon theme.

---

data/amethyst/Preset.toml

change tooltip color

---

data/blobfox/Preset.toml

Add Blobfox theme

---

data/forgejo-dark/Preset.toml

Add forgejo-dark

---

data/twitch-theme/Preset.toml

Add Twitch theme

---

data/nord-dark/Preset.toml

add nord dark theme

---

data/discord/Preset.toml

add Discord theme

---

data/classic-xp/Preset.toml

This Pull Request adds the Classic XP theme made by @neptuner on revolt. Nothing else, nothing more :3

Add Classic XP theme

---

data/vintage-terminal/Preset.toml

feat: add Vintage Terminal theme

---

data/catppuccin-frappe/Custom.css
data/catppuccin-frappe/Preset.toml
data/catppuccin-latte/Custom.css
data/catppuccin-latte/Preset.toml
data/catppuccin-macchiato/Custom.css
data/catppuccin-macchiato/Preset.toml
data/catppuccin-mocha/Custom.css
data/catppuccin-mocha/Preset.toml

feat: add catppuccin

---

data/blossom/Preset.toml

feat: add Blossom theme

---

data/axo/Custom.css
data/axo/Preset.toml

Link: https://unsplash.com/photos/Bkci_8qcdvQ
License: https://unsplash.com/license

feat: add Axo theme

---

data/glass/Custom.css
data/nucleon/Custom.css

per discussion in revolt development channel

Remove "(Disables theme)" text from Nucleon and Glass

---

data/kyli0x/Preset.toml

add kyli0x theme

---

data/lucifers-fall/Custom.css
data/lucifers-fall/Preset.toml

Add Lucifer's Fall

---

data/social-classic/Custom.css
data/social-classic/Preset.toml

A theme inspired in social websites from the 2010s, mixing light and dark elements with a prominent use of a primary color. Said color can be easily customized through the accent color picker in the Appearance settings.
This theme includes custom CSS.

Add Social Classic theme

---

data/purpel/Custom.css
data/purpel/Preset.toml

The URL import in the custom CSS is fine because you can't change permalinked gist content without also having the URL change

Add purpel theme

---

data/iceshrimp-light/Custom.css
data/iceshrimp-light/Preset.toml

Fix error, warning, and success colours to match upstream IceShrimp theme

---

data/dark-purple-theme/Preset.toml

Added a Dark Purple theme, like in official JetBrains extension
Ref.
[Dark Purple Theme](https://github.com/OlyaB/DarkPurpleTheme)

feat: Add "Dark Purple" theme

---

data/blood-and-rust/Preset.toml

Fixed some spelling errors, and also changed the formatting based on other themes so it should be cleaner now maybe.

Fixed (hopefully) Blood and Rust theme

---

data/sakura-midnight/Preset.toml

Suggestion on adding theme: "Sakura Midnight"

---

data/sakura-midnight/Preset.toml

Updated the Author from Kiyoshi#5907 to Mia#5907.
Changed version v0.0.2 > v0.0.3

Updated Preset.toml

---

data/material-dark/Preset.toml
data/material-light/Custom.css
data/material-light/Preset.toml

Fixed the wrong colors on Material Dark and made a Light version of the theme.
(I still get confused doing pull requests so, sorry if I make mistakes while doing pull requests.)

Material Light Theme and Color Fixes for Material Dark

---

data/solarized-light/Preset.toml

add solarized light theme
